version: '2'
services:
    web:
      restart: always
      #指定镜像创建源目录，在其根目录中必须包含Dockerfile
      build: ./superlists/
      # 多行命令
      command: bash -c "python3 manage.py makemigrations
                        && python3 manage.py migrate
                        && python3 manage.py runserver 8000"
      # 端口映射(host:container)
      ports:
        - "8000:8000"
      # 指定你要挂载的容器卷,路径可任意
      volumes:
        - /code
      # 指定要进行相互间通信的容器名
      links:
        - db
        - redis

    nginx:
      restart: always
      build: ./nginx/
      ports:
        - "80:80"
      environment:
        - NGINX_HOST_1="www.klinlee.com"
        - NGINX_PORT=80
        - WEB_CONTAINER_NAME = web
      # nginx容器挂载在与web容器相同的容器卷上
      volumes_from:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/mysite.template
      links:
        - web:web
      command:
        /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    db:
      restart: always
      image: postgres:latest
      volumes:
        - ./data/postgresql:/var/lib/postgresql/data

    redis:
      restart: always
      image: redis:latest
      volumes:
        - /data
